services:
  ewmdb:
    image: postgres:16.1
    container_name: ewmdb
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck: # Добавляем healthcheck для проверки готовности базы данных
      test: [ "CMD-SHELL", "pg_isready -U admin -d ewmdb" ] # Используем pg_isready
      interval: 10s # Проверка каждые 10 секунд
      timeout: 5s  # Таймаут 5 секунд
      retries: 3  # 3 попытки

  ewm-service:
    build:
      context: ./ewm-main-svc
    image: ewm-service
    container_name: ewm-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewmdb:5432/ewmdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: postgres
    ports:
      - "8080:8080"
    depends_on:
      ewmdb: # Явно указываем зависимость от ewmdb
        condition: service_healthy # Ждем, пока ewmdb не станет healthy
      stats-server: # Явно указываем зависимость от stats-server
        condition: service_healthy # Ждем, пока stats-server не станет healthy

  stats-server:
    build:
      context: ./stat-svc/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      statdb: # Явно указываем зависимость от statdb
        condition: service_healthy # Ждем, пока statdb не станет healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  statdb:
    image: postgres:16.1
    container_name: statdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=statdb
    healthcheck: # Добавляем healthcheck для statdb
      test: [ "CMD-SHELL", "pg_isready -U admin -d statdb" ] # Проверяем statdb
      interval: 10s
      timeout: 5s
      retries: 3
